# Generated by Django 5.1.6 on 2025-08-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_slug'),
    ]

    operations = [
    ]
