# Generated by Django 5.1.6 on 2025-08-18 14:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_comment_options_alter_recipe_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('cake', 'Cake'), ('pastry', 'Pastry'), ('bread', 'Bread')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['recipe', 'user'], name='recipes_lik_recipe__ea3c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['created_at'], name='recipes_lik_created_5aa8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['status', 'created_at'], name='recipes_rec_status_da9330_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category', 'created_at'], name='recipes_rec_categor_b800af_idx'),
        ),
    ]
